omake = [ "Chapter 11: Omake Files 1, 2, 3", "Chapter 64: Omake Files 4, Alternate Parallels",]

[paths]
source = "../book-src"
target = "../target"
extension = "html"

[strip]
selectors = [ "meta[name=\"generator\"]", "script", "div#access", "div#nav-top", "div#nav-bottom", "div#footer",]

[metadata]
chapter_title = "div#chapter-title"
story_container = "div#storycontent"

[author_notes]
"Chapter 1: A Day of Very Low Probability" = 73
"Chapter 10: Self Awareness, Part II" = 12
"Chapter 100: Precautionary Measures, Pt 1" = 0
"Chapter 101: Precautionary Measures, Pt 2" = 0
"Chapter 102: Caring" = 0
"Chapter 103: Tests" = 0
"Chapter 104: The Truth, Pt 1, Riddles and Answers" = 0
"Chapter 105: The Truth, Pt 2" = 0
"Chapter 106: The Truth, Pt 3" = 0
"Chapter 107: The Truth, Pt 4" = 0
"Chapter 108: The Truth, Pt 5, Answers and Riddles" = 0
"Chapter 109: Reflections" = 0
"Chapter 110: Reflections, Pt 2" = 0
"Chapter 111: Failure, Pt 1" = 0
"Chapter 112: Failure, Pt 2" = 0
"Chapter 113: Final Exam" = 0
"Chapter 114: Shut Up and Do The Impossible" = 0
"Chapter 115: Shut Up and Do The Impossible, Pt 2" = 5
"Chapter 116: Aftermath, Something to Protect, Pt 0" = 0
"Chapter 119: Something to Protect: Albus Dumbledore" = 0
"Chapter 12: Impulse Control" = 4
"Chapter 120: Something to Protect: Draco Malfoy" = 38
"Chapter 117: Something to Protect: Minerva McGonagall" = 0
"Chapter 118: Something to Protect: Professor Quirrell" = 0
"Chapter 121: Something to Protect: Severus Snape" = 0
"Chapter 122: Something to Protect: Hermione Granger" = 0
"Chapter 13: Asking the Wrong Questions" = 7
"Chapter 14: The Unknown and the Unknowable" = 4
"Chapter 15: Conscientiousness" = 7
"Chapter 16: Lateral Thinking" = 4
"Chapter 17: Locating the Hypothesis" = 7
"Chapter 18: Dominance Hierarchies" = 4
"Chapter 19: Delayed Gratification" = 4
"Chapter 2: Everything I Believe Is False" = 4
"Chapter 20: Bayes's Theorem" = 4
"Chapter 21: Rationalization" = 4
"Chapter 22: The Scientific Method" = 80
"Chapter 23: Belief in Belief" = 4
"Chapter 24: Machiavellian Intelligence Hypothesis" = 4
"Chapter 25: Hold Off on Proposing Solutions" = 13
"Chapter 26: Noticing Confusion" = 4
"Chapter 27: Empathy" = 7
"Chapter 28: Reductionism" = 13
"Chapter 29: Egocentric Bias" = 7
"Chapter 3: Comparing Reality To Its Alternatives" = 4
"Chapter 30: Working in Groups, Pt 1" = 4
"Chapter 31: Working in Groups, Pt 2" = 0
"Chapter 32: Interlude: Personal Financial Management" = 0
"Chapter 33: Coordination Problems, Pt 1" = 13
"Chapter 34: Coordination Problems, Pt 2" = 0
"Chapter 35: Coordination Problems, Pt 3" = 0
"Chapter 36: Status Differentials" = 0
"Chapter 37: Interlude: Crossing the Boundary" = 0
"Chapter 38: The Cardinal Sin" = 0
"Chapter 39: Pretending to be Wise, Pt 1" = 0
"Chapter 4: The Efficient Market Hypothesis" = 7
"Chapter 40: Pretending to be Wise, Pt 2" = 0
"Chapter 41: Frontal Override" = 0
"Chapter 42: Courage" = 0
"Chapter 43: Humanism, Pt 1" = 0
"Chapter 44: Humanism, Pt 2" = 0
"Chapter 45: Humanism, Pt 3" = 0
"Chapter 46: Humanism, Pt 4" = 0
"Chapter 47: Personhood Theory" = 0
"Chapter 48: Utilitarian Priorities" = 0
"Chapter 49: Prior Information" = 0
"Chapter 5: The Fundamental Attribution Error" = 4
"Chapter 50: Self Centeredness" = 0
"Chapter 51: Title Redacted, Pt 1" = 0
"Chapter 52: The Stanford Prison Experiment, Pt 2" = 0
"Chapter 53: The Stanford Prison Experiment, Pt 3" = 0
"Chapter 54: The Stanford Prison Experiment, Pt 4" = 0
"Chapter 55: The Stanford Prison Experiment, Pt 5" = 0
"Chapter 56: TSPE, Constrained Optimization, Pt 6" = 0
"Chapter 57: TSPE, Constrained Cognition, Pt 7" = 0
"Chapter 58: TSPE, Constrained Cognition, Pt 8" = 16
"Chapter 59: TSPE, Curiosity, Pt 9" = 0
"Chapter 6: The Planning Fallacy" = 10
"Chapter 60: The Stanford Prison Experiment, Pt 10" = 0
"Chapter 61: TSPE, Secrecy and Openness, Pt 11" = 0
"Chapter 62: The Stanford Prison Experiment, Final" = 0
"Chapter 63: TSPE, Aftermaths" = 0
"Chapter 65: Contagious Lies" = 0
"Chapter 66: Self Actualization, Pt 1" = 0
"Chapter 67: Self Actualization, Pt 2" = 0
"Chapter 68: Self Actualization, Pt 3" = 0
"Chapter 69: Self Actualization, Pt 4" = 0
"Chapter 7: Reciprocation" = 21
"Chapter 70: Self Actualization, Pt 5" = 0
"Chapter 71: Self Actualization, Pt 6" = 0
"Chapter 72: SA, Plausible Deniability, Pt 7" = 0
"Chapter 73: SA, The Sacred and the Mundane, Pt 8" = 0
"Chapter 74: SA, Escalation of Conflicts, Pt 9" = 0
"Chapter 75: Self Actualization Final, Responsibility" = 0
"Chapter 76: Interlude with the Confessor: Sunk Costs" = 0
"Chapter 77: SA, Aftermaths: Surface Appearances" = 0
"Chapter 78: Taboo Tradeoffs Prelude: Cheating" = 0
"Chapter 79: Taboo Tradeoffs, Pt 1" = 0
"Chapter 8: Positive Bias" = 18
"Chapter 80: Taboo Tradeoffs, Pt 2, The Horns Effect" = 0
"Chapter 81: Taboo Tradeoffs, Pt 3" = 0
"Chapter 82: Taboo Tradeoffs, Final" = 0
"Chapter 83: Taboo Tradeoffs, Aftermath 1" = 0
"Chapter 84: Taboo Tradeoffs, Aftermath 2" = 0
"Chapter 85: Taboo Tradeoffs, Aftermath 3, Distance" = 5
"Chapter 86: Multiple Hypothesis Testing" = 0
"Chapter 87: Hedonic Awareness" = 0
"Chapter 88: Time Pressure, Pt 1" = 0
"Chapter 89: Time Pressure, Pt 2" = 0
"Chapter 9: Title Redacted, Part I" = 18
"Chapter 90: Roles, Pt 1" = 0
"Chapter 91: Roles, Pt 2" = 8
"Chapter 92: Roles, Pt 3" = 0
"Chapter 93: Roles, Pt 4" = 0
"Chapter 94: Roles, Pt 5" = 0
"Chapter 95: Roles, Pt 6" = 0
"Chapter 96: Roles, Pt 7" = 5
"Chapter 97: Roles, Pt 8" = 0
"Chapter 98: Roles, Final" = 0
"Chapter 99: Roles, Aftermath" = 0

[footnotes]
"Chapter 104: The Truth, Pt 1, Riddles and Answers" = 1240
"Chapter 105: The Truth, Pt 2" = 341
"Chapter 106: The Truth, Pt 3" = 172
"Chapter 107: The Truth, Pt 4" = 446
"Chapter 109: Reflections" = 501
"Chapter 110: Reflections, Pt 2" = 194
"Chapter 111: Failure, Pt 1" = 1041
"Chapter 112: Failure, Pt 2" = 123
"Chapter 113: Final Exam" = 280
"Chapter 114: Shut Up and Do The Impossible" = 325
"Chapter 115: Shut Up and Do The Impossible, Pt 2" = 395
"Chapter 116: Aftermath, Something to Protect, Pt 0" = 262
"Chapter 1: A Day of Very Low Probability" = -1
"Chapter 10: Self Awareness, Part II" = -1
"Chapter 100: Precautionary Measures, Pt 1" = -1
"Chapter 101: Precautionary Measures, Pt 2" = -1
"Chapter 102: Caring" = -1
"Chapter 103: Tests" = -1
"Chapter 108: The Truth, Pt 5, Answers and Riddles" = -1
"Chapter 119: Something to Protect: Albus Dumbledore" = 1020
"Chapter 12: Impulse Control" = -1
"Chapter 120: Something to Protect: Draco Malfoy" = 266
"Chapter 117: Something to Protect: Minerva McGonagall" = 185
"Chapter 118: Something to Protect: Professor Quirrell" = 95
"Chapter 121: Something to Protect: Severus Snape" = 153
"Chapter 122: Something to Protect: Hermione Granger" = 1145
"Chapter 13: Asking the Wrong Questions" = -1
"Chapter 14: The Unknown and the Unknowable" = -1
"Chapter 15: Conscientiousness" = -1
"Chapter 16: Lateral Thinking" = -1
"Chapter 17: Locating the Hypothesis" = -1
"Chapter 18: Dominance Hierarchies" = -1
"Chapter 19: Delayed Gratification" = -1
"Chapter 2: Everything I Believe Is False" = -1
"Chapter 20: Bayes's Theorem" = -1
"Chapter 21: Rationalization" = -1
"Chapter 22: The Scientific Method" = -1
"Chapter 23: Belief in Belief" = -1
"Chapter 24: Machiavellian Intelligence Hypothesis" = -1
"Chapter 25: Hold Off on Proposing Solutions" = -1
"Chapter 26: Noticing Confusion" = -1
"Chapter 27: Empathy" = -1
"Chapter 28: Reductionism" = -1
"Chapter 29: Egocentric Bias" = -1
"Chapter 3: Comparing Reality To Its Alternatives" = -1
"Chapter 30: Working in Groups, Pt 1" = -1
"Chapter 31: Working in Groups, Pt 2" = -1
"Chapter 32: Interlude: Personal Financial Management" = -1
"Chapter 33: Coordination Problems, Pt 1" = -1
"Chapter 34: Coordination Problems, Pt 2" = -1
"Chapter 35: Coordination Problems, Pt 3" = -1
"Chapter 36: Status Differentials" = -1
"Chapter 37: Interlude: Crossing the Boundary" = -1
"Chapter 38: The Cardinal Sin" = -1
"Chapter 39: Pretending to be Wise, Pt 1" = -1
"Chapter 4: The Efficient Market Hypothesis" = -1
"Chapter 40: Pretending to be Wise, Pt 2" = -1
"Chapter 41: Frontal Override" = -1
"Chapter 42: Courage" = -1
"Chapter 43: Humanism, Pt 1" = -1
"Chapter 44: Humanism, Pt 2" = -1
"Chapter 45: Humanism, Pt 3" = -1
"Chapter 46: Humanism, Pt 4" = -1
"Chapter 47: Personhood Theory" = -1
"Chapter 48: Utilitarian Priorities" = -1
"Chapter 49: Prior Information" = -1
"Chapter 5: The Fundamental Attribution Error" = -1
"Chapter 50: Self Centeredness" = -1
"Chapter 51: Title Redacted, Pt 1" = -1
"Chapter 52: The Stanford Prison Experiment, Pt 2" = -1
"Chapter 53: The Stanford Prison Experiment, Pt 3" = -1
"Chapter 54: The Stanford Prison Experiment, Pt 4" = -1
"Chapter 55: The Stanford Prison Experiment, Pt 5" = -1
"Chapter 56: TSPE, Constrained Optimization, Pt 6" = -1
"Chapter 57: TSPE, Constrained Cognition, Pt 7" = -1
"Chapter 58: TSPE, Constrained Cognition, Pt 8" = -1
"Chapter 59: TSPE, Curiosity, Pt 9" = -1
"Chapter 6: The Planning Fallacy" = -1
"Chapter 60: The Stanford Prison Experiment, Pt 10" = -1
"Chapter 61: TSPE, Secrecy and Openness, Pt 11" = -1
"Chapter 62: The Stanford Prison Experiment, Final" = -1
"Chapter 63: TSPE, Aftermaths" = -1
"Chapter 65: Contagious Lies" = -1
"Chapter 66: Self Actualization, Pt 1" = -1
"Chapter 67: Self Actualization, Pt 2" = -1
"Chapter 68: Self Actualization, Pt 3" = -1
"Chapter 69: Self Actualization, Pt 4" = -1
"Chapter 7: Reciprocation" = -1
"Chapter 70: Self Actualization, Pt 5" = -1
"Chapter 71: Self Actualization, Pt 6" = -1
"Chapter 72: SA, Plausible Deniability, Pt 7" = -1
"Chapter 73: SA, The Sacred and the Mundane, Pt 8" = -1
"Chapter 74: SA, Escalation of Conflicts, Pt 9" = -1
"Chapter 75: Self Actualization Final, Responsibility" = -1
"Chapter 76: Interlude with the Confessor: Sunk Costs" = -1
"Chapter 77: SA, Aftermaths: Surface Appearances" = -1
"Chapter 78: Taboo Tradeoffs Prelude: Cheating" = -1
"Chapter 79: Taboo Tradeoffs, Pt 1" = -1
"Chapter 8: Positive Bias" = -1
"Chapter 80: Taboo Tradeoffs, Pt 2, The Horns Effect" = -1
"Chapter 81: Taboo Tradeoffs, Pt 3" = -1
"Chapter 82: Taboo Tradeoffs, Final" = -1
"Chapter 83: Taboo Tradeoffs, Aftermath 1" = -1
"Chapter 84: Taboo Tradeoffs, Aftermath 2" = -1
"Chapter 85: Taboo Tradeoffs, Aftermath 3, Distance" = -1
"Chapter 86: Multiple Hypothesis Testing" = -1
"Chapter 87: Hedonic Awareness" = -1
"Chapter 88: Time Pressure, Pt 1" = -1
"Chapter 89: Time Pressure, Pt 2" = -1
"Chapter 9: Title Redacted, Part I" = -1
"Chapter 90: Roles, Pt 1" = -1
"Chapter 91: Roles, Pt 2" = -1
"Chapter 92: Roles, Pt 3" = -1
"Chapter 93: Roles, Pt 4" = -1
"Chapter 94: Roles, Pt 5" = -1
"Chapter 95: Roles, Pt 6" = -1
"Chapter 96: Roles, Pt 7" = -1
"Chapter 97: Roles, Pt 8" = -1
"Chapter 98: Roles, Final" = -1
"Chapter 99: Roles, Aftermath" = -1
