[paths]
source = "../book-src"
target = "../target"
extension = "html"

[strip]
selectors = [
    "meta[name=\"generator\"]",
    "script",
    "div#access",
    "div#nav-top",
    "div#nav-bottom",
    "div#footer",
]

[metadata]
chapter_title = "div#chapter-title"
story_container = "div#storycontent"
formatter_suffix = "hr"